<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns1="http://www.vertexinc.com/oseries/services/LookupTaxAreas90" xmlns:vev="urn:vertexinc:o-series:tps:9:0" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.vertexinc.com/oseries/services/LookupTaxAreas90">
  <wsdl:types>
    <xsd:schema>
      <xsd:import namespace="urn:vertexinc:o-series:tps:9:0" schemaLocation="../xsd/9.0/VertexInc_Envelope.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="lookupTaxAreasRequest">
    <wsdl:part element="vev:VertexEnvelope" name="inDoc"/>
  </wsdl:message>
  <wsdl:message name="lookupTaxAreasResponse">
    <wsdl:part element="vev:VertexEnvelope" name="VertexEnvelope"/>
  </wsdl:message>
  <wsdl:portType name="LookupTaxAreasWS90">
    <wsdl:operation name="LookupTaxAreas90">
      <wsdl:input message="tns1:lookupTaxAreasRequest" name="lookupTaxAreasRequest"/>
      <wsdl:output message="tns1:lookupTaxAreasResponse" name="lookupTaxAreasResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="LookupTaxAreas90SoapBinding" type="tns1:LookupTaxAreasWS90">
    <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="LookupTaxAreas90">
      <wsdlsoap:operation soapAction=""/>
      <wsdl:input name="lookupTaxAreasRequest">
        <wsdlsoap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="lookupTaxAreasResponse">
        <wsdlsoap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="LookupTaxAreasWSService90">
    <wsdl:port binding="tns1:LookupTaxAreas90SoapBinding" name="LookupTaxAreas90">
      <wsdlsoap:address location="http://bmcdv1dbap03:8095/vertex-ws/services/LookupTaxAreas90"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>